version: "2"

services:

  bhotel_memcached:
    image: memcached:latest
    container_name: bhotel_memcached
    networks:
      main:
        ipv4_address: 172.18.0.4

  bhotel_mysql_5_5:
    image: mysql:5.5
    container_name: bhotel_mysql_5_5
    volumes:
      - ${MYSQL_5_5_DB_PATH}:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      main:
        ipv4_address: 172.18.0.2

  bhotel_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: bhotel_phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: bhotel_mysql_5_5
    networks:
      main:
        ipv4_address: 172.18.0.3

  # ------------------------
  #webserver:
  #      image: nginx:alpine
  #      container_name: webserver
  #      working_dir: /application
  #      volumes:
  #          - ../development/web/:/application
  #          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  #          - ./logs/nginx:/var/log/nginx
  #      ports:
  #       - "80:80"
  #      links:
  #       - php53
  #       - php54
  #       - php56

  bhotel_webserver:
    container_name: bhotel_webserver
    image: nginx:alpine
    volumes:
      - ./nginx-sites:/etc/nginx/conf.d
      - ${LOGS_NGINX_PATH}:/var/log/nginx
      - ${BHOTEL_PROJECT_PATH}:/var/www/html
      - ${SANDBOX_PROJECT_PATH}:/var/www/html/application
      - ${API_PROJECT_PATH}:/var/www/html/api
      - ${SPBRIDGE_PROJECT_PATH}:/var/www/html/sp-mbt-bridge
    links:
      - bhotel
      - bhotel_sandbox
      - bhotel_mbt_api
      - bhotel_mbt_sp_bridge
      #- widgets
    networks:
      main:
        ipv4_address: 172.18.0.6

  # ------------------------

  bhotel:
    build:
      context: .
      dockerfile: php53/Dockerfile
    container_name: bhotel
    working_dir: /var/www/html
    volumes:
      - ${BHOTEL_PROJECT_PATH}:/var/www/html
    links:
      - bhotel_memcached
      - bhotel_mysql_5_5
    networks:
      main:
        ipv4_address: 172.18.0.5
    extra_hosts:
      - "api.dev.lt:172.18.0.6"
      - "spbridge.dev.lt:172.18.0.6"

  bhotel_mbt_api:
    build:
      context: .
      dockerfile: php56/Dockerfile
    container_name: bhotel_mbt_api
    working_dir: /var/www/html
    volumes:
      - ${API_PROJECT_PATH}:/var/www/html/api
      - ${SSH_KEY_PATH}:/root/.ssh/id_rsa:ro
    links:
      - bhotel_mysql_5_5
    networks:
      main:
        ipv4_address: 172.18.0.8
    extra_hosts:
      - "bhotel.dev.lt:172.18.0.6"
      - "spbridge.dev.lt:172.18.0.6"

  bhotel_mbt_sp_bridge:
    build:
      context: .
      dockerfile: php56/Dockerfile
    container_name: bhotel_mbt_sp_bridge
    working_dir: /var/www/html
    volumes:
      - ${SPBRIDGE_PROJECT_PATH}:/var/www/html/sp-mbt-bridge
      - ${SSH_KEY_PATH}:/root/.ssh/id_rsa:ro
    links:
      - bhotel_mysql_5_5
    networks:
      main:
        ipv4_address: 172.18.0.9
    extra_hosts:
      - "bhotel.dev.lt:172.18.0.6"
      - "api.dev.lt:172.18.0.6"


  bhotel_sandbox:
    build:
      context: .
      dockerfile: php56/Dockerfile
    container_name: bhotel_sandbox
    working_dir: /var/www/html/application
    volumes:
      - ${SANDBOX_PROJECT_PATH}:/var/www/html/application
      - ./php56/php-ini-overrides.ini:/etc/php5/fpm/conf.d/php-ini-overrides.ini
    links:
      - bhotel_memcached
      - bhotel_mysql_5_5
    networks:
      main:
        ipv4_address: 172.18.0.7

networks:
  main:
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1